{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-test/2.2.255-SNAPSHOT/kotlin-test-2.2.255-SNAPSHOT.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.2.255-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-js-2.2.255-SNAPSHOT.klib",
          "url": "kotlin-test-js-2.2.255-SNAPSHOT.klib",
          "size": 138591,
          "sha512": "e4da80f0497b3a05ec0b20b2a09c175e5b3576dcbe6c08c4ab03c1a4bc0c49bd9ab5edd56771c38a6d05807ab7b90458dce48faf2fd444cc54d11c4f59228425",
          "sha256": "1e9a4dd0a0b958cb082b211da47829a11ac553182f57c205187adb5e9d047e93",
          "sha1": "3c50da44842b99310764b99cca11ffb2ebd38fda",
          "md5": "23258230bb07400ed28dae03796ecc5a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.klib.packaging": "packed",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-js-2.2.255-SNAPSHOT.klib",
          "url": "kotlin-test-js-2.2.255-SNAPSHOT.klib",
          "size": 138591,
          "sha512": "e4da80f0497b3a05ec0b20b2a09c175e5b3576dcbe6c08c4ab03c1a4bc0c49bd9ab5edd56771c38a6d05807ab7b90458dce48faf2fd444cc54d11c4f59228425",
          "sha256": "1e9a4dd0a0b958cb082b211da47829a11ac553182f57c205187adb5e9d047e93",
          "sha1": "3c50da44842b99310764b99cca11ffb2ebd38fda",
          "md5": "23258230bb07400ed28dae03796ecc5a"
        }
      ]
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "kotlin-test-js-2.2.255-SNAPSHOT-sources.jar",
          "url": "kotlin-test-js-2.2.255-SNAPSHOT-sources.jar",
          "size": 60830,
          "sha512": "9ae24e1d6168c955736c271eece8ca56a1dd6a9499ebc87d34008560fa393895e9e8fc3a118edd13b5ccf1d5978e1041d42aebcfce6f476b97114a08a8b0785f",
          "sha256": "462595119cd6a6c6e50ac061af8ad9e4e2d08d0557b935795d2f9cb615bf96bf",
          "sha1": "8695631e45215b30d180e83b34480f3e5dba92d1",
          "md5": "77a526df1c19060d4fb66758fbedd9d6"
        }
      ]
    }
  ]
}
