{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-gradle-plugin-model",
    "version": "2.2.255-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-sources.jar",
          "size": 16086,
          "sha512": "04f4b0729f8330b50a8991a5950e5f954a73a7be78163a3ec88911c4134f1f2c1fab6ced18c164b3f3db7a4129753f13940ec839cb5d82157077552e812a77c9",
          "sha256": "73b20f45829dc34ed0a393ccb199b60d777bdf7ac46b8542e613e05981b39e7b",
          "sha1": "2c51cfcf7532ed574df3166870461168b794bc9b",
          "md5": "1dd4c54ed70e688e586431976be7ea8d"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ]
    },
    {
      "name": "gradle80SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle80-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle80-sources.jar",
          "size": 16086,
          "sha512": "04f4b0729f8330b50a8991a5950e5f954a73a7be78163a3ec88911c4134f1f2c1fab6ced18c164b3f3db7a4129753f13940ec839cb5d82157077552e812a77c9",
          "sha256": "73b20f45829dc34ed0a393ccb199b60d777bdf7ac46b8542e613e05981b39e7b",
          "sha1": "2c51cfcf7532ed574df3166870461168b794bc9b",
          "md5": "1dd4c54ed70e688e586431976be7ea8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle80",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle80ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle80.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle80.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle80",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle80RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle80.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle80.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle80",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle81SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle81-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle81-sources.jar",
          "size": 16086,
          "sha512": "04f4b0729f8330b50a8991a5950e5f954a73a7be78163a3ec88911c4134f1f2c1fab6ced18c164b3f3db7a4129753f13940ec839cb5d82157077552e812a77c9",
          "sha256": "73b20f45829dc34ed0a393ccb199b60d777bdf7ac46b8542e613e05981b39e7b",
          "sha1": "2c51cfcf7532ed574df3166870461168b794bc9b",
          "md5": "1dd4c54ed70e688e586431976be7ea8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle81",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle81ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle81.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle81.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle81",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle81RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle81.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle81.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle81",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle82SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle82-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle82-sources.jar",
          "size": 16086,
          "sha512": "04f4b0729f8330b50a8991a5950e5f954a73a7be78163a3ec88911c4134f1f2c1fab6ced18c164b3f3db7a4129753f13940ec839cb5d82157077552e812a77c9",
          "sha256": "73b20f45829dc34ed0a393ccb199b60d777bdf7ac46b8542e613e05981b39e7b",
          "sha1": "2c51cfcf7532ed574df3166870461168b794bc9b",
          "md5": "1dd4c54ed70e688e586431976be7ea8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle82",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle82ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle82.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle82.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle82",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle82RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle82.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle82.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle82",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle85SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle85-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle85-sources.jar",
          "size": 16086,
          "sha512": "04f4b0729f8330b50a8991a5950e5f954a73a7be78163a3ec88911c4134f1f2c1fab6ced18c164b3f3db7a4129753f13940ec839cb5d82157077552e812a77c9",
          "sha256": "73b20f45829dc34ed0a393ccb199b60d777bdf7ac46b8542e613e05981b39e7b",
          "sha1": "2c51cfcf7532ed574df3166870461168b794bc9b",
          "md5": "1dd4c54ed70e688e586431976be7ea8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle85",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle85ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle85.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle85.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle85",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle85RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle85.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle85.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle85",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle86SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle86-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle86-sources.jar",
          "size": 16086,
          "sha512": "04f4b0729f8330b50a8991a5950e5f954a73a7be78163a3ec88911c4134f1f2c1fab6ced18c164b3f3db7a4129753f13940ec839cb5d82157077552e812a77c9",
          "sha256": "73b20f45829dc34ed0a393ccb199b60d777bdf7ac46b8542e613e05981b39e7b",
          "sha1": "2c51cfcf7532ed574df3166870461168b794bc9b",
          "md5": "1dd4c54ed70e688e586431976be7ea8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle86",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle86ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle86"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle86.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle86.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle86",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle86RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle86"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle86.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle86.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle86",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle88SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle88-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle88-sources.jar",
          "size": 16086,
          "sha512": "04f4b0729f8330b50a8991a5950e5f954a73a7be78163a3ec88911c4134f1f2c1fab6ced18c164b3f3db7a4129753f13940ec839cb5d82157077552e812a77c9",
          "sha256": "73b20f45829dc34ed0a393ccb199b60d777bdf7ac46b8542e613e05981b39e7b",
          "sha1": "2c51cfcf7532ed574df3166870461168b794bc9b",
          "md5": "1dd4c54ed70e688e586431976be7ea8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle88",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle88ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle88"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle88.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle88.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle88",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle88RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle88"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle88.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle88.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle88",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle811SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle811-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle811-sources.jar",
          "size": 16086,
          "sha512": "04f4b0729f8330b50a8991a5950e5f954a73a7be78163a3ec88911c4134f1f2c1fab6ced18c164b3f3db7a4129753f13940ec839cb5d82157077552e812a77c9",
          "sha256": "73b20f45829dc34ed0a393ccb199b60d777bdf7ac46b8542e613e05981b39e7b",
          "sha1": "2c51cfcf7532ed574df3166870461168b794bc9b",
          "md5": "1dd4c54ed70e688e586431976be7ea8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle811",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle811ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle811"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle811.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle811.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle811",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle811RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle811"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle811.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle811.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle811",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle813SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle813-sources.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle813-sources.jar",
          "size": 16086,
          "sha512": "04f4b0729f8330b50a8991a5950e5f954a73a7be78163a3ec88911c4134f1f2c1fab6ced18c164b3f3db7a4129753f13940ec839cb5d82157077552e812a77c9",
          "sha256": "73b20f45829dc34ed0a393ccb199b60d777bdf7ac46b8542e613e05981b39e7b",
          "sha1": "2c51cfcf7532ed574df3166870461168b794bc9b",
          "md5": "1dd4c54ed70e688e586431976be7ea8d"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle813",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle813ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle813"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle813.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle813.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle813",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle813RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle813"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle813.jar",
          "url": "kotlin-gradle-plugin-model-2.2.255-SNAPSHOT-gradle813.jar",
          "size": 21586,
          "sha512": "5884de57546e2fc5fc33e759618b9302e7170c803d217c3e4b714c3df85ae514323e9b93727cc441f015756364710e5b9aa1e8c3286dd85ccbfa22187d879df4",
          "sha256": "b6711402a6042fde437b5b3072cb759d55930b19f981e36ed6337ede8bdc72f0",
          "sha1": "43838c26b7d628de05343bb1b18250f121594f68",
          "md5": "abb6f386c82a64f376295bdff6ca9852"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-gradle-plugin-model-gradle813",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    }
  ]
}
