{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "fus-statistics-gradle-plugin",
    "version": "2.2.255-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-sources.jar",
          "size": 29656,
          "sha512": "af48e6320d04cad36715584ae9936c73c05a6a58aace35047b55baac24deb6f7c75a3ed204edacdcf5f3bb381910b9e7cee79021304b66bee837261bd0229083",
          "sha256": "d936b6067978d1f4d1e2c6ba89cb569d242382642ff64c535cd6c046e0ca1ff0",
          "sha1": "79bcec8a5a477de74f9b76f870974950bae17f46",
          "md5": "a73f2d1ed8ef43c555a244c4bb177d20"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ]
    },
    {
      "name": "gradle80SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle80-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle80-sources.jar",
          "size": 29656,
          "sha512": "af48e6320d04cad36715584ae9936c73c05a6a58aace35047b55baac24deb6f7c75a3ed204edacdcf5f3bb381910b9e7cee79021304b66bee837261bd0229083",
          "sha256": "d936b6067978d1f4d1e2c6ba89cb569d242382642ff64c535cd6c046e0ca1ff0",
          "sha1": "79bcec8a5a477de74f9b76f870974950bae17f46",
          "md5": "a73f2d1ed8ef43c555a244c4bb177d20"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle80ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle80.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle80.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle80RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle80.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle80.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle81SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle81-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle81-sources.jar",
          "size": 29656,
          "sha512": "af48e6320d04cad36715584ae9936c73c05a6a58aace35047b55baac24deb6f7c75a3ed204edacdcf5f3bb381910b9e7cee79021304b66bee837261bd0229083",
          "sha256": "d936b6067978d1f4d1e2c6ba89cb569d242382642ff64c535cd6c046e0ca1ff0",
          "sha1": "79bcec8a5a477de74f9b76f870974950bae17f46",
          "md5": "a73f2d1ed8ef43c555a244c4bb177d20"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle81ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle81.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle81.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle81RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle81.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle81.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle82SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle82-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle82-sources.jar",
          "size": 29656,
          "sha512": "af48e6320d04cad36715584ae9936c73c05a6a58aace35047b55baac24deb6f7c75a3ed204edacdcf5f3bb381910b9e7cee79021304b66bee837261bd0229083",
          "sha256": "d936b6067978d1f4d1e2c6ba89cb569d242382642ff64c535cd6c046e0ca1ff0",
          "sha1": "79bcec8a5a477de74f9b76f870974950bae17f46",
          "md5": "a73f2d1ed8ef43c555a244c4bb177d20"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle82ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle82.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle82.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle82RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle82.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle82.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle85SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle85-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle85-sources.jar",
          "size": 29656,
          "sha512": "af48e6320d04cad36715584ae9936c73c05a6a58aace35047b55baac24deb6f7c75a3ed204edacdcf5f3bb381910b9e7cee79021304b66bee837261bd0229083",
          "sha256": "d936b6067978d1f4d1e2c6ba89cb569d242382642ff64c535cd6c046e0ca1ff0",
          "sha1": "79bcec8a5a477de74f9b76f870974950bae17f46",
          "md5": "a73f2d1ed8ef43c555a244c4bb177d20"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle85ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle85.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle85.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle85RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle85.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle85.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle86SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle86-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle86-sources.jar",
          "size": 29656,
          "sha512": "af48e6320d04cad36715584ae9936c73c05a6a58aace35047b55baac24deb6f7c75a3ed204edacdcf5f3bb381910b9e7cee79021304b66bee837261bd0229083",
          "sha256": "d936b6067978d1f4d1e2c6ba89cb569d242382642ff64c535cd6c046e0ca1ff0",
          "sha1": "79bcec8a5a477de74f9b76f870974950bae17f46",
          "md5": "a73f2d1ed8ef43c555a244c4bb177d20"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle86ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle86"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle86.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle86.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle86RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle86"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle86.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle86.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle88SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle88-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle88-sources.jar",
          "size": 29656,
          "sha512": "af48e6320d04cad36715584ae9936c73c05a6a58aace35047b55baac24deb6f7c75a3ed204edacdcf5f3bb381910b9e7cee79021304b66bee837261bd0229083",
          "sha256": "d936b6067978d1f4d1e2c6ba89cb569d242382642ff64c535cd6c046e0ca1ff0",
          "sha1": "79bcec8a5a477de74f9b76f870974950bae17f46",
          "md5": "a73f2d1ed8ef43c555a244c4bb177d20"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle88ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle88"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle88.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle88.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle88RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle88"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle88.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle88.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle811SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle811-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle811-sources.jar",
          "size": 29656,
          "sha512": "af48e6320d04cad36715584ae9936c73c05a6a58aace35047b55baac24deb6f7c75a3ed204edacdcf5f3bb381910b9e7cee79021304b66bee837261bd0229083",
          "sha256": "d936b6067978d1f4d1e2c6ba89cb569d242382642ff64c535cd6c046e0ca1ff0",
          "sha1": "79bcec8a5a477de74f9b76f870974950bae17f46",
          "md5": "a73f2d1ed8ef43c555a244c4bb177d20"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle811ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle811"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle811.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle811.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle811RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle811"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle811.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle811.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle813SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle813-sources.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle813-sources.jar",
          "size": 29656,
          "sha512": "af48e6320d04cad36715584ae9936c73c05a6a58aace35047b55baac24deb6f7c75a3ed204edacdcf5f3bb381910b9e7cee79021304b66bee837261bd0229083",
          "sha256": "d936b6067978d1f4d1e2c6ba89cb569d242382642ff64c535cd6c046e0ca1ff0",
          "sha1": "79bcec8a5a477de74f9b76f870974950bae17f46",
          "md5": "a73f2d1ed8ef43c555a244c4bb177d20"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle813ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle813"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle813.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle813.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle813RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle813"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle813.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-gradle813.jar",
          "size": 159672,
          "sha512": "5f74805160b47a1b781ef6718250dcaa48f1758d5514c20b9e1d4b09ec5208451721cba19e11d643240e7ce03e79ef8925d7c1aa0cf4185a0cb05b7cedd264f1",
          "sha256": "636816dd47e8197cb49e6513f0494a9207cc2e67153d565a7bd0beb4e6858831",
          "sha1": "f4d72f58de3c1b7e4014739bae2368e0da077562",
          "md5": "88174cfe2879e64c13502bc45dd9f273"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "fus-statistics-gradle-plugin",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-javadoc.jar",
          "url": "fus-statistics-gradle-plugin-2.2.255-SNAPSHOT-javadoc.jar",
          "size": 257,
          "sha512": "2dd30c1b0f576649990edb3feb381d1bd9528a540dad44bd53066ba0f9e755f096a8cda8b1f9bd5c349ccb2c2a636ae75da1d72ab399b6e7bfea76c2d43665e8",
          "sha256": "4200a274bbbdfe19ef5418d3013075dddaca4d2f14c85bade6652dc6d8ad42ce",
          "sha1": "a3977689da6c6aaef495bd2d3fd8bc990fa7f2e0",
          "md5": "0d8fbffcbd5c9c755debe1fe381fe6b5"
        }
      ]
    }
  ]
}
