{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "atomicfu",
    "version": "2.2.255-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-sources.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-sources.jar",
          "size": 5050,
          "sha512": "5059b7a20b8bea9f88e78af19bfd1e2189182c8d1f86f69371b8167eaf3cd9c21dcaa3e602463b7ab159bb5077d1fce26b2c5d55c5d64f67f9e006838376b924",
          "sha256": "094c86b103566e6a079b2fcba5aac75eab2762f7693654ddffe29465dddffa4e",
          "sha1": "0ee15b17743a1291e4064586d831d39e8cc69d7d",
          "md5": "fffc890e8d185b565366fe059af054f1"
        }
      ]
    },
    {
      "name": "runtimeElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ]
    },
    {
      "name": "apiElementsWithFixedAttribute",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugins-bom",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ]
    },
    {
      "name": "gradle80SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle80-sources.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle80-sources.jar",
          "size": 5050,
          "sha512": "5059b7a20b8bea9f88e78af19bfd1e2189182c8d1f86f69371b8167eaf3cd9c21dcaa3e602463b7ab159bb5077d1fce26b2c5d55c5d64f67f9e006838376b924",
          "sha256": "094c86b103566e6a079b2fcba5aac75eab2762f7693654ddffe29465dddffa4e",
          "sha1": "0ee15b17743a1291e4064586d831d39e8cc69d7d",
          "md5": "fffc890e8d185b565366fe059af054f1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle80ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle80.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle80.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle80RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.0",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle80"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle80.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle80.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle81SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle81-sources.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle81-sources.jar",
          "size": 5050,
          "sha512": "5059b7a20b8bea9f88e78af19bfd1e2189182c8d1f86f69371b8167eaf3cd9c21dcaa3e602463b7ab159bb5077d1fce26b2c5d55c5d64f67f9e006838376b924",
          "sha256": "094c86b103566e6a079b2fcba5aac75eab2762f7693654ddffe29465dddffa4e",
          "sha1": "0ee15b17743a1291e4064586d831d39e8cc69d7d",
          "md5": "fffc890e8d185b565366fe059af054f1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle81ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle81.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle81.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle81RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.1",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle81"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle81.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle81.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle82SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle82-sources.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle82-sources.jar",
          "size": 5050,
          "sha512": "5059b7a20b8bea9f88e78af19bfd1e2189182c8d1f86f69371b8167eaf3cd9c21dcaa3e602463b7ab159bb5077d1fce26b2c5d55c5d64f67f9e006838376b924",
          "sha256": "094c86b103566e6a079b2fcba5aac75eab2762f7693654ddffe29465dddffa4e",
          "sha1": "0ee15b17743a1291e4064586d831d39e8cc69d7d",
          "md5": "fffc890e8d185b565366fe059af054f1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle82ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle82.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle82.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle82RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.2",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle82"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle82.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle82.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle85SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle85-sources.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle85-sources.jar",
          "size": 5050,
          "sha512": "5059b7a20b8bea9f88e78af19bfd1e2189182c8d1f86f69371b8167eaf3cd9c21dcaa3e602463b7ab159bb5077d1fce26b2c5d55c5d64f67f9e006838376b924",
          "sha256": "094c86b103566e6a079b2fcba5aac75eab2762f7693654ddffe29465dddffa4e",
          "sha1": "0ee15b17743a1291e4064586d831d39e8cc69d7d",
          "md5": "fffc890e8d185b565366fe059af054f1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle85ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle85.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle85.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle85RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.5",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle85"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle85.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle85.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle86SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle86-sources.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle86-sources.jar",
          "size": 5050,
          "sha512": "5059b7a20b8bea9f88e78af19bfd1e2189182c8d1f86f69371b8167eaf3cd9c21dcaa3e602463b7ab159bb5077d1fce26b2c5d55c5d64f67f9e006838376b924",
          "sha256": "094c86b103566e6a079b2fcba5aac75eab2762f7693654ddffe29465dddffa4e",
          "sha1": "0ee15b17743a1291e4064586d831d39e8cc69d7d",
          "md5": "fffc890e8d185b565366fe059af054f1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle86ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle86"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle86.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle86.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle86RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.6",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle86"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle86.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle86.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle88SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle88-sources.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle88-sources.jar",
          "size": 5050,
          "sha512": "5059b7a20b8bea9f88e78af19bfd1e2189182c8d1f86f69371b8167eaf3cd9c21dcaa3e602463b7ab159bb5077d1fce26b2c5d55c5d64f67f9e006838376b924",
          "sha256": "094c86b103566e6a079b2fcba5aac75eab2762f7693654ddffe29465dddffa4e",
          "sha1": "0ee15b17743a1291e4064586d831d39e8cc69d7d",
          "md5": "fffc890e8d185b565366fe059af054f1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle88ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle88"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle88.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle88.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle88RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.8",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle88"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle88.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle88.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle811SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle811-sources.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle811-sources.jar",
          "size": 5050,
          "sha512": "5059b7a20b8bea9f88e78af19bfd1e2189182c8d1f86f69371b8167eaf3cd9c21dcaa3e602463b7ab159bb5077d1fce26b2c5d55c5d64f67f9e006838376b924",
          "sha256": "094c86b103566e6a079b2fcba5aac75eab2762f7693654ddffe29465dddffa4e",
          "sha1": "0ee15b17743a1291e4064586d831d39e8cc69d7d",
          "md5": "fffc890e8d185b565366fe059af054f1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle811ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle811"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle811.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle811.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle811RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.11",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle811"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle811.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle811.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle813SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle813-sources.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle813-sources.jar",
          "size": 5050,
          "sha512": "5059b7a20b8bea9f88e78af19bfd1e2189182c8d1f86f69371b8167eaf3cd9c21dcaa3e602463b7ab159bb5077d1fce26b2c5d55c5d64f67f9e006838376b924",
          "sha256": "094c86b103566e6a079b2fcba5aac75eab2762f7693654ddffe29465dddffa4e",
          "sha1": "0ee15b17743a1291e4064586d831d39e8cc69d7d",
          "md5": "fffc890e8d185b565366fe059af054f1"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle813ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle813"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle813.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle813.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "gradle813RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.13",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin-api",
          "version": {
            "requires": "2.2.255-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-reflect"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-script-runtime"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            }
          ],
          "requestedCapabilities": [
            {
              "group": "org.jetbrains.kotlin",
              "name": "kotlin-gradle-plugin-api-gradle813"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-gradle813.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-gradle813.jar",
          "size": 15193,
          "sha512": "3c8a78820d0170e23516c9aa88ab91b260aae8e5499f52607880c86263d736be4a2b51e2e98a76c23f11257c9e0abbda90f5b5acafa70e0aa5ff3450dcdc515d",
          "sha256": "511f9177fcc42623e730b3cdbf129ad99e2504881711041e1d57aa79538d9a57",
          "sha1": "98062dc041f3348cae23ddff4a1306c64235ed71",
          "md5": "9a567fb44f4457e495622f63dc5050e4"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "atomicfu",
          "version": "2.2.255-SNAPSHOT"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomicfu-2.2.255-SNAPSHOT-javadoc.jar",
          "url": "atomicfu-2.2.255-SNAPSHOT-javadoc.jar",
          "size": 257,
          "sha512": "2dd30c1b0f576649990edb3feb381d1bd9528a540dad44bd53066ba0f9e755f096a8cda8b1f9bd5c349ccb2c2a636ae75da1d72ab399b6e7bfea76c2d43665e8",
          "sha256": "4200a274bbbdfe19ef5418d3013075dddaca4d2f14c85bade6652dc6d8ad42ce",
          "sha1": "a3977689da6c6aaef495bd2d3fd8bc990fa7f2e0",
          "md5": "0d8fbffcbd5c9c755debe1fe381fe6b5"
        }
      ]
    }
  ]
}
